# Generated by Django 2.2.24 on 2021-11-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_fill_db"),
        ("mainapp", "0002_product"),
    ]

    operations = []
