# Generated by Django 2.2.24 on 2021-12-15 00:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20211212_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 0, 47, 46, 357902, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
